services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: test
    image: tjpnick/web:latest
    ports:
      - "3000:3000"
    volumes:
      - "./node_modules:/srv/app/node_modules"
