services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    image: ktiprog.azurecr.io/skiscratcher/web:latest
    ports:
      - "80:3000"
    volumes:
      - "./node_modules:/srv/app/node_modules"
