version: "3.8"
services:
  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    image: tjpnick/db:latest
    volumes:
      - "./backend/init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ktinventory
    ports:
      - "3306:3306"
    restart: always
  web:
    build: ./backend
    image: tjpnick/web:latest
    environment:
      MYSQL_DATABASE: ktinventory
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db